from __future__ import annotations

from pathlib import Path

import numpy as np

from ..utils import ensure_parent


def export_obj(vertices: np.ndarray, faces: np.ndarray, path: str | Path) -> Path:
    """Write a simple Wavefront OBJ file.

    This deliberately avoids magic. For starter forms, a plain OBJ writer makes
    it easier to inspect the generated geometry and debug malformed faces.
    """
    p = ensure_parent(path)
    vertices = np.asarray(vertices, dtype=float)
    faces = np.asarray(faces, dtype=int)

    with p.open("w", encoding="utf-8") as f:
        f.write("# Generated by DSP Form Lab\n")
        for x, y, z in vertices:
            f.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
        for face in faces:
            # OBJ face indices are 1-based.
            idx = [int(i) + 1 for i in face]
            f.write("f " + " ".join(str(i) for i in idx) + "\n")
    return p


def export_with_trimesh(vertices: np.ndarray, faces: np.ndarray, path: str | Path) -> Path:
    """Export through trimesh when available.

    Useful for STL/PLY/GLB later. OBJ remains the baseline exchange target.
    """
    import trimesh

    p = ensure_parent(path)
    mesh = trimesh.Trimesh(vertices=np.asarray(vertices), faces=np.asarray(faces), process=False)
    mesh.export(p)
    return p
