from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np

from .audio_features import AudioFeatures
from .utils import ensure_parent, normalize, stable_seed, utc_now_iso, write_json


def _safe_float(value: float, *, digits: int = 3) -> str:
    """Format floats compactly for EisenScript output."""
    return f"{float(value):.{digits}f}".rstrip("0").rstrip(".")


def _local_peaks(values: np.ndarray, *, threshold: float, max_events: int) -> list[int]:
    """Return local peak frame indices above threshold, sorted by time.

    This is intentionally small and dependency-free. It is not meant to replace
    a full onset picker; it just turns an onset envelope into a manageable set
    of StructureSynth growth calls.
    """
    arr = np.asarray(values, dtype=float)
    if len(arr) == 0:
        return []
    peaks: list[int] = []
    for idx in range(1, len(arr) - 1):
        if arr[idx] >= threshold and arr[idx] >= arr[idx - 1] and arr[idx] >= arr[idx + 1]:
            peaks.append(idx)
    if not peaks:
        peaks = [int(np.argmax(arr))]
    if len(peaks) > max_events:
        # Keep the strongest peaks, then restore chronological order.
        strongest = sorted(peaks, key=lambda i: arr[i], reverse=True)[:max_events]
        peaks = sorted(strongest)
    return peaks


def summarize_for_structuresynth(features: AudioFeatures, *, onset_threshold: float = 0.62) -> dict[str, Any]:
    """Summarize audio features into grammar-level controls."""
    rms = normalize(features.rms)
    centroid = normalize(features.centroid)
    bandwidth = normalize(features.bandwidth)
    onset = normalize(features.onset)

    frame_count = max(1, len(features.times))
    peak_indices = _local_peaks(onset, threshold=onset_threshold, max_events=64)
    onset_density = min(1.0, len(peak_indices) / max(1, frame_count / 8.0))

    return {
        "rms_mean": float(np.mean(rms)) if len(rms) else 0.0,
        "rms_max": float(np.max(rms)) if len(rms) else 0.0,
        "centroid_mean": float(np.mean(centroid)) if len(centroid) else 0.0,
        "bandwidth_mean": float(np.mean(bandwidth)) if len(bandwidth) else 0.0,
        "onset_mean": float(np.mean(onset)) if len(onset) else 0.0,
        "onset_max": float(np.max(onset)) if len(onset) else 0.0,
        "onset_threshold": float(onset_threshold),
        "onset_count": int(len(peak_indices)),
        "onset_density": float(onset_density),
        "frame_count": int(frame_count),
        "peak_indices": [int(i) for i in peak_indices],
    }


def generate_eisenscript(
    features: AudioFeatures,
    *,
    seed: int = 0,
    template: str = "onset-lattice",
    max_events: int = 24,
    onset_threshold: float = 0.62,
) -> tuple[str, dict[str, Any]]:
    """Generate a StructureSynth/EisenScript grammar from audio features.

    The current template uses the captured WAV as a *score* for recursive
    growth. RMS controls scale, onset peaks instantiate event nodes, centroid
    chooses low/mid/high rule families, and bandwidth controls spread.
    """
    if template != "onset-lattice":
        raise ValueError("Only template='onset-lattice' is implemented in this starter repo.")

    rng_seed = stable_seed(seed)
    summary = summarize_for_structuresynth(features, onset_threshold=onset_threshold)
    rms = normalize(features.rms)
    centroid = normalize(features.centroid)
    bandwidth = normalize(features.bandwidth)
    onset = normalize(features.onset)

    peaks = _local_peaks(onset, threshold=onset_threshold, max_events=max_events)
    if len(peaks) == 0 and len(onset) > 0:
        peaks = [int(np.argmax(onset))]

    energy = summary["rms_mean"]
    brightness = summary["centroid_mean"]
    roughness = summary["bandwidth_mean"]
    density = summary["onset_density"]

    maxdepth = int(20 + 18 * energy + 10 * density)
    maxobjects = int(900 + 4500 * density + 1600 * roughness)
    trunk_scale = 0.75 + 1.2 * energy
    trunk_step = 0.7 + 0.6 * energy
    trunk_decay = 0.965 - 0.05 * roughness
    branch_angle = 10 + 42 * brightness
    twist = 6 + 80 * roughness
    branch_decay = 0.72 + 0.16 * (1.0 - roughness)
    detail_scale = 0.14 + 0.38 * max(0.05, brightness)

    lines: list[str] = []
    lines.extend(
        [
            "/*",
            "  Generated by dsp-form-lab.",
            "  StructureSynth lane: captured WAV -> audio features -> EisenScript grammar.",
            "  Treat this as a grammar score, not as the final printable mesh.",
            "*/",
            f"set seed {rng_seed}",
            f"set maxdepth {maxdepth}",
            f"set maxobjects {maxobjects}",
            "set background white",
            "main",
            "",
            "rule main {",
            f"  {{ s {_safe_float(trunk_scale)} }} trunk",
        ]
    )

    duration = max(features.duration_seconds, 1e-6)
    for event_number, idx in enumerate(peaks):
        t_norm = float(features.times[idx] / duration) if idx < len(features.times) else 0.0
        e = float(rms[idx]) if idx < len(rms) else energy
        c = float(centroid[idx]) if idx < len(centroid) else brightness
        b = float(bandwidth[idx]) if idx < len(bandwidth) else roughness
        o = float(onset[idx]) if idx < len(onset) else 0.0

        # Spread event calls in a shallow arc. The transforms remain simple so
        # they are easy to edit directly inside StructureSynth.
        x = -12.0 + 24.0 * t_norm
        y = (c - 0.5) * 8.0
        z = 0.7 + event_number * 0.18 + e * 1.3
        scale = 0.32 + 1.15 * e + 0.35 * o
        rz = -42.0 + 84.0 * t_norm + twist * 0.15
        ry = -18.0 + 36.0 * c

        if c < 0.34:
            rule_name = "event_low"
        elif c < 0.68:
            rule_name = "event_mid"
        else:
            rule_name = "event_high"

        # Add one line per captured event. These lines are the clearest place to
        # hand-edit the sonic structure after generation.
        lines.append(
            "  "
            + f"{{ x {_safe_float(x)} y {_safe_float(y)} z {_safe_float(z)} "
            + f"rz {_safe_float(rz)} ry {_safe_float(ry)} s {_safe_float(scale)} }} {rule_name}"
        )

    lines.extend(
        [
            "}",
            "",
            f"rule trunk maxdepth {max(6, int(maxdepth * 0.45))} {{",
            f"  {{ s {_safe_float(0.42 + 0.5 * energy)} }} sphere",
            f"  {{ x {_safe_float(trunk_step)} rz {_safe_float(twist * 0.22)} ry {_safe_float(branch_angle * 0.28)} s {_safe_float(trunk_decay)} }} trunk",
            f"  {{ x {_safe_float(trunk_step * 0.72)} rz {_safe_float(-branch_angle)} ry {_safe_float(branch_angle * 0.7)} s {_safe_float(branch_decay)} }} branch",
            f"  {{ x {_safe_float(trunk_step * 0.64)} rz {_safe_float(branch_angle)} ry {_safe_float(-branch_angle * 0.55)} s {_safe_float(branch_decay * 0.94)} }} branch",
            "}",
            "",
            f"rule branch maxdepth {max(4, int(6 + density * 8))} {{",
            f"  {{ s {_safe_float(0.28 + 0.45 * roughness)} }} box",
            f"  {{ x {_safe_float(0.55 + 0.35 * energy)} rz {_safe_float(branch_angle)} ry {_safe_float(twist * 0.2)} s {_safe_float(branch_decay)} }} branch",
            f"  {{ x {_safe_float(0.46 + 0.25 * brightness)} rz {_safe_float(-branch_angle * 0.8)} ry {_safe_float(-twist * 0.16)} s {_safe_float(branch_decay * 0.9)} }} twig",
            "}",
            "",
            f"rule twig maxdepth {max(3, int(4 + density * 6))} {{",
            f"  {{ s {_safe_float(detail_scale)} }} sphere",
            f"  {{ x {_safe_float(0.38 + 0.22 * brightness)} rz {_safe_float(twist * 0.35)} ry {_safe_float(branch_angle * 0.45)} s {_safe_float(0.72 + 0.12 * energy)} }} twig",
            "}",
            "",
            "rule event_low maxdepth 6 {",
            f"  {{ s {_safe_float(0.74 + energy)} }} sphere",
            f"  {{ x {_safe_float(0.78 + energy)} rz {_safe_float(-18 - twist * 0.18)} ry {_safe_float(8 + branch_angle * 0.2)} s {_safe_float(0.82)} }} event_low",
            "}",
            "",
            "rule event_mid maxdepth 7 {",
            f"  {{ s {_safe_float(0.45 + roughness)} }} box",
            f"  {{ x {_safe_float(0.68 + roughness)} rz {_safe_float(branch_angle)} ry {_safe_float(12 + brightness * 25)} s {_safe_float(0.8)} }} event_mid",
            f"  {{ x {_safe_float(0.54)} rz {_safe_float(-branch_angle * 0.85)} s {_safe_float(0.62 + 0.18 * energy)} }} twig",
            "}",
            "",
            "rule event_high maxdepth 5 {",
            f"  {{ s {_safe_float(0.22 + brightness * 0.42)} }} sphere",
            f"  {{ x {_safe_float(0.46 + brightness * 0.34)} rz {_safe_float(34 + twist * 0.45)} ry {_safe_float(18 + branch_angle * 0.35)} s {_safe_float(0.72)} }} event_high",
            f"  {{ x {_safe_float(0.35)} rz {_safe_float(-52 - twist * 0.2)} s {_safe_float(0.48 + 0.22 * roughness)} }} sparkle",
            "}",
            "",
            "rule sparkle maxdepth 2 {",
            f"  {{ s {_safe_float(max(0.08, detail_scale * 0.55))} }} sphere",
            "}",
            "",
        ]
    )

    metadata = {
        "template": template,
        "seed": rng_seed,
        "max_events": int(max_events),
        "event_count_written": int(len(peaks)),
        "summary": {k: v for k, v in summary.items() if k != "peak_indices"},
        "grammar_parameters": {
            "maxdepth": maxdepth,
            "maxobjects": maxobjects,
            "trunk_scale": trunk_scale,
            "trunk_step": trunk_step,
            "trunk_decay": trunk_decay,
            "branch_angle": branch_angle,
            "twist": twist,
            "branch_decay": branch_decay,
            "detail_scale": detail_scale,
        },
    }
    return "\n".join(lines), metadata


def write_structuresynth_grammar(
    features: AudioFeatures,
    out_path: str | Path,
    *,
    seed: int = 0,
    template: str = "onset-lattice",
    max_events: int = 24,
    onset_threshold: float = 0.62,
) -> dict[str, Any]:
    """Write an EisenScript grammar and sidecar manifest."""
    path = ensure_parent(out_path)
    grammar, metadata = generate_eisenscript(
        features,
        seed=seed,
        template=template,
        max_events=max_events,
        onset_threshold=onset_threshold,
    )
    path.write_text(grammar, encoding="utf-8")

    manifest_path = path.with_suffix(".json")
    manifest: dict[str, Any] = {
        "created_utc": utc_now_iso(),
        "generator": "structuresynth/onset-lattice",
        "seed": stable_seed(seed),
        "parameters": {
            "template": template,
            "max_events": max_events,
            "onset_threshold": onset_threshold,
        },
        "audio": features.to_manifest(),
        "structuresynth": metadata,
        "outputs": {
            "eisenscript": str(path),
            "manifest": str(manifest_path),
            "expected_next_step": "Open the .es file in StructureSynth or BrowserSynth, export OBJ, then inspect/repair like any other generated mesh.",
        },
    }
    write_json(manifest_path, manifest)
    return manifest
